apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml


images:
- name: webhook-server
  newName: quay.io/rh-ee-tnewman/myrepo
  newTag: webhook-test
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: webhook-server
