apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- networkpolicy-default-deny.yaml
- networkpolicy-controller.yaml
- networkpolicy-webhook.yaml
- networkpolicy-build-and-sign.yaml
